# This script is used for testing the functionality of the UHN library
* It is important to update this test scritpt with updates in the UHN library
* It is important to also update this script to show what each cell tests
* It is important to test all aspects of the library

In [7]:
import UHN as UHN
import numpy as np

In [5]:
# data pattern
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
query = [3, 2, 3]
print(data, "data stored\n")
print(query, "query stored\n")

model = UHN.UHNModel(UHN.manhattan, UHN.softmax, UHN.weighted_sum, iterator = False, quiet = False)
model.fit(data)
model.query(np.array(query))

[[1 2 3]
 [4 5 6]
 [7 8 9]] data stored

[3, 2, 3] query stored

data stored for Manhattan separator
data stored for Weighted Sum projection
Manhattan similarity flow complete
Softmax separator flow complete
Weighted Sum projection applied


[1.0200835590891117, 2.0200835590891115, 3.020083559089111]

In [6]:
# data pattern
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
query = [3, 2, 3]
print(data, "data stored\n")
print(query, "query stored\n")

# similarity 
similarity = UHN.manhattan(show_progress = False)
similarity.fit(data)
out1 = similarity.flow(np.array(query))
print(out1, "smaller numbers represent similarity\n")

# sepration
probs = UHN.softmax(show_progress = True, invert_probabilities = True)
out2 = probs.flow(out1)
print(out2, "probability of query corresponding to data patterns\n")

# projection
proj = UHN.weighted_sum(show_progress = True)
proj.fit(data)
out3 = proj.flow(out2)
print(out3, "this is the recalled data\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] data stored

[3, 2, 3] query stored

[14  9  0] smaller numbers represent similarity

Softmax separator flow complete
[9.93306306e-01 6.69286776e-03 8.25970499e-07] probability of query corresponding to data patterns

data stored for Weighted Sum projection
Weighted Sum projection applied
[1.0200835590891117, 2.0200835590891115, 3.020083559089111] this is the recalled data

